server:
  port: 9090

jwt:
  secret: "493358340235739058340598340598340598340598340598"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. Seguridad y Autenticación
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # 2. Catálogo (Categorías y Productos)
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/categorias/**, /api/v1/productos/**

        # 3. Inventario
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/inventario/**

        # 4. Clientes (Customer)
        - id: customer-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/customers/**

        # 5. Pagos (Payment)
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/payments/**

        # 6. Promociones (Promo)
        - id: promo-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/promos/**

        # 7. Despachos (Shipping)
        - id: shipping-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/shippings/**

        # 8. Notificaciones
        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/notifications/**

        # 9. Ventas
        - id: sales-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/ventas/**

        # 10. Compras (Proveedores)
        - id: purchasing-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/compras/**

        # 11. Analíticas
        - id: analytics-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/analiticas/**

# Configuración Centralizada de Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    use-root-path: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: 1. Auth Service
        url: /auth/v3/api-docs
      - name: 2. Catalog Service
        url: /api/v1/productos/v3/api-docs
      - name: 3. Inventory Service
        url: /api/v1/inventario/v3/api-docs
      - name: 4. Customer Service
        url: /api/v1/customers/v3/api-docs
      - name: 5. Payment Service
        url: /api/v1/payments/v3/api-docs
      - name: 6. Promo Service
        url: /api/v1/promos/v3/api-docs
      - name: 7. Shipping Service
        url: /api/v1/shippings/v3/api-docs
      - name: 8. Notification Service
        url: /api/v1/notifications/v3/api-docs
      - name: 9. Sales Service
        url: /api/v1/ventas/v3/api-docs
      - name: 10. Purchasing Service
        url: /api/v1/compras/v3/api-docs
      - name: 11. Analytics Service
        url: /api/v1/analiticas/v3/api-docs