spring.application.name=service-promo
server.port=8086

# Conexión a Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_promos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Configuración de Swagger
springdoc.api-docs.path=/api/v1/promos/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html