spring.application.name=analiticas

server.port=8091

#CONEXIÓN db_analiticas

spring.datasource.url=jdbc:mysql://localhost:3306/db_analiticas
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

springdoc.api-docs.path=/api/v1/analiticas/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html